# Generated by Django 2.0.5 on 2018-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=10)),
                ('date_birth', models.DateField()),
                ('state_origin', models.CharField(choices=[('Ab', 'Abia'), ('Ad', 'Adamawa'), ('Ak', 'AkwaIbom'), ('An', 'Anambra'), ('Ba', 'Bauchi'), ('By', 'Bayelsa'), ('Be', 'Benue'), ('Br', 'Borno'), ('Cr', 'Cross-River'), ('Dt', 'Delta'), ('Eb', 'Ebonyi'), ('Ed', 'Edo'), ('En', 'Enugu'), ('Ek', 'Ekiti'), ('Gb', 'Gombe'), ('Im', 'Imo'), ('Ji', 'Jigawa'), ('Kd', 'Kaduna'), ('Ka', 'kano'), ('Kt', 'Katisna'), ('Kb', 'Kebi'), ('kg', 'Kogi'), ('Kw', 'Kwara'), ('La', 'Lagos'), ('Na', 'Nasarawa'), ('Ng', 'Niger'), ('Og', 'Ogun'), ('Oy', 'Oyo'), ('Pl', 'Plateau'), ('Rv', 'Rivers'), ('Sk', 'Sokoro'), ('Tb', 'Taraba'), ('Yb', 'Yobe'), ('Zm', 'Zamfara')], max_length=10)),
                ('local_govt', models.CharField(max_length=20)),
                ('nationalty', models.CharField(default='Nigeria', max_length=10)),
                ('phone_no', models.CharField(help_text='+23480xxxxxxxxxx', max_length=13)),
                ('email', models.EmailField(help_text='user@example.com', max_length=254)),
                ('home_address', models.CharField(max_length=20)),
                ('office_address', models.CharField(max_length=20)),
                ('state_re', models.CharField(choices=[('Ab', 'Abia'), ('Ad', 'Adamawa'), ('Ak', 'AkwaIbom'), ('An', 'Anambra'), ('Ba', 'Bauchi'), ('By', 'Bayelsa'), ('Be', 'Benue'), ('Br', 'Borno'), ('Cr', 'Cross-River'), ('Dt', 'Delta'), ('Eb', 'Ebonyi'), ('Ed', 'Edo'), ('En', 'Enugu'), ('Ek', 'Ekiti'), ('Gb', 'Gombe'), ('Im', 'Imo'), ('Ji', 'Jigawa'), ('Kd', 'Kaduna'), ('Ka', 'kano'), ('Kt', 'Katisna'), ('Kb', 'Kebi'), ('kg', 'Kogi'), ('Kw', 'Kwara'), ('La', 'Lagos'), ('Na', 'Nasarawa'), ('Ng', 'Niger'), ('Og', 'Ogun'), ('Oy', 'Oyo'), ('Pl', 'Plateau'), ('Rv', 'Rivers'), ('Sk', 'Sokoro'), ('Tb', 'Taraba'), ('Yb', 'Yobe'), ('Zm', 'Zamfara')], max_length=10)),
                ('town', models.CharField(max_length=10)),
            ],
        ),
    ]
