# Generated by Django 2.0.5 on 2018-08-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='state_re',
            new_name='state',
        ),
    ]
