# Generated by Django 2.0.5 on 2018-08-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_auto_20180820_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nationalty',
            field=models.CharField(default='Nigeria', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(choices=[('Ab', 'Abia'), ('Ad', 'Adamawa'), ('Ak', 'AkwaIbom'), ('An', 'Anambra'), ('Ba', 'Bauchi'), ('By', 'Bayelsa'), ('Be', 'Benue'), ('Br', 'Borno'), ('Cr', 'Cross-River'), ('Dt', 'Delta'), ('Eb', 'Ebonyi'), ('Ed', 'Edo'), ('En', 'Enugu'), ('Ek', 'Ekiti'), ('Gb', 'Gombe'), ('Im', 'Imo'), ('Ji', 'Jigawa'), ('Kd', 'Kaduna'), ('Ka', 'kano'), ('Kt', 'Katisna'), ('Kb', 'Kebi'), ('kg', 'Kogi'), ('Kw', 'Kwara'), ('La', 'Lagos'), ('Na', 'Nasarawa'), ('Ng', 'Niger'), ('Og', 'Ogun'), ('Oy', 'Oyo'), ('Pl', 'Plateau'), ('Rv', 'Rivers'), ('Sk', 'Sokoro'), ('Tb', 'Taraba'), ('Yb', 'Yobe'), ('Zm', 'Zamfara'), ('Os', 'Osun')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state_origin',
            field=models.CharField(choices=[('Ab', 'Abia'), ('Ad', 'Adamawa'), ('Ak', 'AkwaIbom'), ('An', 'Anambra'), ('Ba', 'Bauchi'), ('By', 'Bayelsa'), ('Be', 'Benue'), ('Br', 'Borno'), ('Cr', 'Cross-River'), ('Dt', 'Delta'), ('Eb', 'Ebonyi'), ('Ed', 'Edo'), ('En', 'Enugu'), ('Ek', 'Ekiti'), ('Gb', 'Gombe'), ('Im', 'Imo'), ('Ji', 'Jigawa'), ('Kd', 'Kaduna'), ('Ka', 'kano'), ('Kt', 'Katisna'), ('Kb', 'Kebi'), ('kg', 'Kogi'), ('Kw', 'Kwara'), ('La', 'Lagos'), ('Na', 'Nasarawa'), ('Ng', 'Niger'), ('Og', 'Ogun'), ('Oy', 'Oyo'), ('Pl', 'Plateau'), ('Rv', 'Rivers'), ('Sk', 'Sokoro'), ('Tb', 'Taraba'), ('Yb', 'Yobe'), ('Zm', 'Zamfara'), ('Os', 'Osun')], max_length=10),
        ),
    ]
