# Generated by Django 2.0.5 on 2018-08-22 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_auto_20180821_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('txn_type', models.CharField(choices=[('dr', 'Debit'), ('cr', 'Credit')], max_length=10, null=True)),
                ('txn_details', models.CharField(max_length=20)),
                ('txn_date', models.DateField(auto_now=True)),
                ('account_id', models.UUIDField(default=uuid.UUID('00010203-0405-0607-0809-0a0b0c0d0e0f'), help_text='Unique ID for user account', primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='passport',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop.UserInfo'),
        ),
    ]
