# Generated by Django 2.0.5 on 2018-08-22 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0005_auto_20180822_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for user account', primary_key=True, serialize=False),
        ),
    ]
