# Generated by Django 2.0.5 on 2018-08-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0007_auto_20180823_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='passport',
        ),
    ]
