# Generated by Django 2.0.5 on 2018-09-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0008_remove_userinfo_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_no',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coop.UserInfo')),
            ],
            bases=('coop.userinfo',),
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='credit',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='account_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='account_owner',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='debit',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='passport',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='txn_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_no',
            field=models.CharField(help_text='+23480xxxxxxxxxx', max_length=20),
        ),
    ]
