# Generated by Django 2.0.5 on 2018-09-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0009_auto_20180907_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='passport',
        ),
    ]
